// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TankerMade.Server.Data;

#nullable disable

namespace TankerMade.Server.Migrations
{
    [DbContext(typeof(TankerMadeDbContext))]
    partial class TankerMadeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TankerMade.Core.Entities.AssetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleKey");

                    b.HasIndex("StoragePath")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("ModuleKey", "RecordType", "RecordId");

                    b.HasIndex("UserId", "ModuleKey", "IsDeleted", "CreatedAt");

                    b.ToTable("CoreAssetRecords", (string)null);
                });

            modelBuilder.Entity("TankerMade.Core.Entities.AssetThumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SizeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetRecordId");

                    b.HasIndex("StoragePath")
                        .IsUnique();

                    b.HasIndex("AssetRecordId", "SizeKey")
                        .IsUnique();

                    b.ToTable("CoreAssetThumbnails", (string)null);
                });

            modelBuilder.Entity("TankerMade.Core.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("TankerMade.Core.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Red",
                            Slug = "red"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Blue",
                            Slug = "blue"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Green",
                            Slug = "green"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Yellow",
                            Slug = "yellow"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Black",
                            Slug = "black"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "White",
                            Slug = "white"
                        });
                });

            modelBuilder.Entity("TankerMade.Core.Entities.ModuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBundled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleKey")
                        .IsUnique();

                    b.ToTable("ModuleDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Live module for 3D printing workflows and data.",
                            IsBundled = true,
                            ModuleKey = "printing-3d",
                            Name = "3D Printing",
                            Version = "0.1.0"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Live module for crochet workflows and data.",
                            IsBundled = true,
                            ModuleKey = "crochet",
                            Name = "Crochet",
                            Version = "0.1.0"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Live module for embroidery workflows and data.",
                            IsBundled = true,
                            ModuleKey = "embroidery",
                            Name = "Embroidery",
                            Version = "0.1.0"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Live module for knitting workflows and data.",
                            IsBundled = true,
                            ModuleKey = "knitting",
                            Name = "Knitting",
                            Version = "0.1.0"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Live module for quilting workflows and data.",
                            IsBundled = true,
                            ModuleKey = "quilting",
                            Name = "Quilting",
                            Version = "0.1.0"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555557"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Live module for sewing workflows and data.",
                            IsBundled = true,
                            ModuleKey = "sewing",
                            Name = "Sewing",
                            Version = "0.1.0"
                        });
                });

            modelBuilder.Entity("TankerMade.Core.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Website",
                            Slug = "website"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Marketplace",
                            Slug = "marketplace"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Video",
                            Slug = "video"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Book",
                            Slug = "book"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Custom",
                            Slug = "custom"
                        });
                });

            modelBuilder.Entity("TankerMade.Core.Entities.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Animals",
                            Slug = "animals"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Baby",
                            Slug = "baby"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home Decor",
                            Slug = "home-decor"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Toys",
                            Slug = "toys"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clothing",
                            Slug = "clothing"
                        });
                });

            modelBuilder.Entity("TankerMade.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TankerMade.Core.Entities.UserModuleActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleDefinitionId");

                    b.HasIndex("UserId", "ModuleDefinitionId")
                        .IsUnique();

                    b.ToTable("UserModuleActivations");
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingInventoryPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSalePrice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("YarnInventoryItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("YarnInventoryItemId");

                    b.ToTable("CraftingInventoryPurchases", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingInventoryReferenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Category", "Slug")
                        .IsUnique();

                    b.HasIndex("Category", "SortOrder");

                    b.ToTable("CraftingInventoryReferenceItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666601"),
                            Category = "yarn-weight",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lace",
                            Slug = "lace",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666602"),
                            Category = "yarn-weight",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fingering",
                            Slug = "fingering",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666603"),
                            Category = "yarn-weight",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DK",
                            Slug = "dk",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666604"),
                            Category = "yarn-weight",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Worsted",
                            Slug = "worsted",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666605"),
                            Category = "yarn-weight",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bulky",
                            Slug = "bulky",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666606"),
                            Category = "fiber-tag",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Synthetic",
                            Slug = "synthetic",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666607"),
                            Category = "fiber-tag",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Natural",
                            Slug = "natural",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666608"),
                            Category = "fiber-tag",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Blended",
                            Slug = "blended",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666609"),
                            Category = "tool-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hook",
                            Slug = "hook",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-66666666660a"),
                            Category = "tool-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Needle",
                            Slug = "needle",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-66666666660b"),
                            Category = "tool-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gauge Ruler",
                            Slug = "gauge-ruler",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-66666666660c"),
                            Category = "tool-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Stitch Holder",
                            Slug = "stitch-holder",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-66666666660d"),
                            Category = "notion-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Button",
                            Slug = "button",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-66666666660e"),
                            Category = "notion-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Stitch Marker",
                            Slug = "stitch-marker",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-66666666660f"),
                            Category = "notion-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tapestry Needle",
                            Slug = "tapestry-needle",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666610"),
                            Category = "notion-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Zipper",
                            Slug = "zipper",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Slug");

                    b.HasIndex("ThemeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsArchived", "Name");

                    b.ToTable("CraftingKits", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingKitPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PatternId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.HasIndex("PatternId");

                    b.HasIndex("KitId", "SortOrder");

                    b.ToTable("CraftingKitPieces", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingKitSupply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.HasIndex("KitId", "SortOrder");

                    b.ToTable("CraftingKitSupplies", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingNotionInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedBrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RegularPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "NormalizedBrandName", "NormalizedTypeName")
                        .IsUnique();

                    b.ToTable("CraftingNotionInventoryItems", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingNotionPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSalePrice")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NotionInventoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotionInventoryItemId");

                    b.ToTable("CraftingNotionPurchases", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.HasIndex("SourceId");

                    b.HasIndex("ThemeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ThemeId", "Name");

                    b.ToTable("CraftingPatterns", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingPatternPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatternId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatternId");

                    b.HasIndex("PatternId", "SortOrder");

                    b.ToTable("CraftingPatternPieces", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingPatternStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatternPieceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RangeStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatternPieceId");

                    b.HasIndex("PatternPieceId", "SortOrder");

                    b.ToTable("CraftingPatternSteps", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("KitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KitPieceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PatternId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("KitId");

                    b.HasIndex("KitPieceId")
                        .IsUnique();

                    b.HasIndex("PatternId");

                    b.HasIndex("Slug");

                    b.HasIndex("ThemeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PatternId");

                    b.HasIndex("UserId", "IsArchived", "Name");

                    b.ToTable("CraftingProjects", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingProjectInventoryLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuantityPlanned")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "InventoryItemType", "InventoryItemId")
                        .IsUnique();

                    b.ToTable("CraftingProjectInventoryLinks", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingProjectStepProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatternStepId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatternStepId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "PatternStepId")
                        .IsUnique();

                    b.ToTable("CraftingProjectStepProgress", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingProjectTimer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ElapsedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatternStepId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatternStepId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "PatternStepId")
                        .IsUnique();

                    b.ToTable("CraftingProjectTimers", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingToolInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedBrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RegularPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "NormalizedBrandName", "NormalizedTypeName")
                        .IsUnique();

                    b.ToTable("CraftingToolInventoryItems", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingToolPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSalePrice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToolInventoryItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolInventoryItemId");

                    b.ToTable("CraftingToolPurchases", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingYarnInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedRemainingLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiberContent")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FiberTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LengthUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainColor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedBrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedColorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegularPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSkeins")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "NormalizedBrandName", "NormalizedColorName")
                        .IsUnique();

                    b.ToTable("CraftingYarnInventoryItems", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingYarnLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentWeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RemainingLength")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Skeins")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("YarnInventoryItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("YarnInventoryItemId");

                    b.HasIndex("YarnInventoryItemId", "LotNumber")
                        .IsUnique();

                    b.ToTable("CraftingYarnLots", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Printing3D.Entities.PrintingInventoryPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSalePrice")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MaterialInventoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialInventoryItemId");

                    b.ToTable("PrintingInventoryPurchases", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Printing3D.Entities.PrintingInventoryReferenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Category", "Slug")
                        .IsUnique();

                    b.HasIndex("Category", "SortOrder");

                    b.ToTable("PrintingInventoryReferenceItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777701"),
                            Category = "material-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PLA",
                            Slug = "pla",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777702"),
                            Category = "material-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PETG",
                            Slug = "petg",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777703"),
                            Category = "material-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "ABS",
                            Slug = "abs",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777704"),
                            Category = "material-type",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TPU",
                            Slug = "tpu",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777705"),
                            Category = "diameter",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "1.75mm",
                            Slug = "1-75mm",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777706"),
                            Category = "diameter",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "2.85mm",
                            Slug = "2-85mm",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777707"),
                            Category = "printer-tooling",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nozzle",
                            Slug = "nozzle",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777708"),
                            Category = "printer-tooling",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Build Plate",
                            Slug = "build-plate",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777709"),
                            Category = "printer-tooling",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Filament Dryer",
                            Slug = "filament-dryer",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-77777777770a"),
                            Category = "printer-tooling",
                            CreatedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scraper",
                            Slug = "scraper",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("TankerMade.Modules.Printing3D.Entities.PrintingMaterialInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedBrandName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedColorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedMaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegularPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RemainingWeightGrams")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSpoolWeightGrams")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "NormalizedMaterialType", "NormalizedBrandName", "NormalizedColorName")
                        .IsUnique();

                    b.ToTable("PrintingMaterialInventoryItems", (string)null);
                });

            modelBuilder.Entity("TankerMade.Modules.Printing3D.Entities.PrintingSpool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialInventoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterCompatibility")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RemainingWeightGrams")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpoolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartingWeightGrams")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialInventoryItemId");

                    b.HasIndex("MaterialInventoryItemId", "SpoolCode")
                        .IsUnique();

                    b.ToTable("PrintingSpools", (string)null);
                });

            modelBuilder.Entity("TankerMade.Core.Entities.AssetRecord", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Core.Entities.AssetThumbnail", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Core.Entities.UserModuleActivation", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.ModuleDefinition", null)
                        .WithMany()
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingInventoryPurchase", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingYarnInventoryItem", null)
                        .WithMany()
                        .HasForeignKey("YarnInventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingKit", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingKitPiece", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingKit", null)
                        .WithMany()
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingPattern", null)
                        .WithMany()
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingKitSupply", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingKit", null)
                        .WithMany()
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingNotionInventoryItem", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingNotionPurchase", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingNotionInventoryItem", null)
                        .WithMany()
                        .HasForeignKey("NotionInventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingPattern", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TankerMade.Core.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingPatternPiece", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingPattern", null)
                        .WithMany()
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingPatternStep", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingPatternPiece", null)
                        .WithMany()
                        .HasForeignKey("PatternPieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingProject", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingKit", null)
                        .WithMany()
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingKitPiece", null)
                        .WithMany()
                        .HasForeignKey("KitPieceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingPattern", null)
                        .WithMany()
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TankerMade.Core.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingProjectInventoryLink", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingProjectStepProgress", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingPatternStep", null)
                        .WithMany()
                        .HasForeignKey("PatternStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingProjectTimer", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingPatternStep", null)
                        .WithMany()
                        .HasForeignKey("PatternStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingToolInventoryItem", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingToolPurchase", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingToolInventoryItem", null)
                        .WithMany()
                        .HasForeignKey("ToolInventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingYarnInventoryItem", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Crafting.Entities.CraftingYarnLot", b =>
                {
                    b.HasOne("TankerMade.Modules.Crafting.Entities.CraftingYarnInventoryItem", null)
                        .WithMany()
                        .HasForeignKey("YarnInventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Printing3D.Entities.PrintingInventoryPurchase", b =>
                {
                    b.HasOne("TankerMade.Modules.Printing3D.Entities.PrintingMaterialInventoryItem", null)
                        .WithMany()
                        .HasForeignKey("MaterialInventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Printing3D.Entities.PrintingMaterialInventoryItem", b =>
                {
                    b.HasOne("TankerMade.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TankerMade.Modules.Printing3D.Entities.PrintingSpool", b =>
                {
                    b.HasOne("TankerMade.Modules.Printing3D.Entities.PrintingMaterialInventoryItem", null)
                        .WithMany()
                        .HasForeignKey("MaterialInventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
